### ISSUE TITLE
 Completely failed to render

### ISSUE THREAD

**Issue by orionlee** [arXiv/html_feedback#1249]
### Description

This paper is not rendered at all:
https://arxiv.org/html/2405.07367v1

### (Optional:) Please add any files, screenshots, or other information here.

![image](https://github.com/arXiv/html_feedback/assets/250644/f16a1b46-bb97-406d-865d-fbd989590123)

---

In developer conosle, there are some error messages
```
addons_new.js:264 Uncaught TypeError: Cannot read properties of null (reading 'prepend')
    at unwrap_nav (addons_new.js:264:9)
    at HTMLDocument.<anonymous> (addons_new.js:314:5)
unwrap_nav @ addons_new.js:264
(anonymous) @ addons_new.js:314
feedbackOverlay.js:52 Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')
    at detectColorScheme (feedbackOverlay.js:52:27)
    at HTMLDocument.<anonymous> (feedbackOverlay.js:68:5)
detectColorScheme @ feedbackOverlay.js:52
(anonymous) @ feedbackOverlay.js:68
feedbackOverlay.js:136 Test theme:null
```

### (Required) What is this issue most closely related to? Select one.

Other

### Internal issue ID

e86655a8-1a64-4392-99cc-c7bcf7f13220

### Paper URL

https://arxiv.org/html/2405.07367v1

### Browser

Chrome/124.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Thank you for your report - the specific issue is now solved.

We have regenerated the article and you should be able to see an improvement.
